# Generated by Django 4.1.7 on 2023-03-07 07:31

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=200)),
                ("platform", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("link", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=200)),
                ("college", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("period", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("firstname", models.CharField(blank=True, max_length=200, null=True)),
                ("lastname", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(max_length=200)),
                ("Message", models.TextField()),
                ("phone", models.IntegerField(blank=True, null=True)),
                (
                    "interests",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DATA SCIENCE", "DATA SCIENCE"),
                            ("DATA ANALYTICS", "DATA ANLYTICS"),
                            ("AGRICULTURAL ENGINEERNG", "AGRICULTURAL ENGINEERING"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField(blank=True, default=False, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("skillname", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DATA SCIENCE", "DATA SCIENCE"),
                            ("DATA ANALYTICS", "DATA ANLYTICS"),
                            ("AGRICULTURAL ENGINEERNG", "AGRICULTURAL ENGINEERING"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                ("linkedin", models.CharField(blank=True, max_length=2000, null=True)),
                ("github", models.CharField(blank=True, max_length=2000, null=True)),
                ("kaggle", models.CharField(blank=True, max_length=2000, null=True)),
                ("facebook", models.CharField(blank=True, max_length=2000, null=True)),
                ("instagram", models.CharField(blank=True, max_length=2000, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("name", models.CharField(max_length=255)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("caption", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DATA SCIENCE", "DATA SCIENCE"),
                            ("DATA ANALYTICS", "DATA ANLYTICS"),
                            ("AGRICULTURAL ENGINEERNG", "AGRICULTURAL ENGINEERING"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        default="/uploads/project/default_thumbnail.jpg",
                        null=True,
                        upload_to=core.models.project_image_file_path,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPLETED", "COMPLETED"),
                            ("ON GOING", "ON GOING"),
                            ("PENDING", "PENDING"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("demo_link", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "github_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "kaggle_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                (
                    "other_source_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("tags", models.ManyToManyField(to="core.tag")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
